language: node_js
node_js:
  - '7'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
