version: 0.0
os: linux
files:
  - source: ./
    destination: /var/apps/teamstudy
hooks:
  AfterInstall:
    - location: deploy/install_dependencies
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: deploy/start_app
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: deploy/stop_app
      timeout: 180
      runas: ubuntu
